sudo: false

os:
  - linux
  - osx

language: d

d:
  - ldc
  - dmd

env:
  - PYTHON_VER=2
  - PYTHON_VER=3

addons:
  apt:
    packages:
    - python-tk
    - python3-tk
    - python-pip
    - python3-pip

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install python$PYTHON_VER; fi
  - pip$PYTHON_VER install matplotlib --user

script:
  - MATPLOTLIB_D_PYTHON=python$PYTHON_VER dub test --compiler=${DC}
